# Generated by Django 3.1.2 on 2020-10-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20201016_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Имя комментатора')),
                ('comment_text', models.CharField(max_length=500, verbose_name='Текст комментария')),
                ('dogovor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.dogovor')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
