# Generated by Django 3.1.2 on 2020-10-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
