# Generated by Django 3.1.2 on 2020-10-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='KT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kt_name', models.CharField(max_length=100, verbose_name='Название этапа')),
                ('kt_status', models.CharField(max_length=20, verbose_name='Статус этапа')),
                ('kt_start', models.CharField(max_length=20, verbose_name='Дата начала')),
                ('kt_end', models.CharField(max_length=20, verbose_name='Дата окончания')),
                ('docs', models.CharField(max_length=20, verbose_name='Документы')),
                ('dogovor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.dogovor')),
            ],
            options={
                'verbose_name': 'Контрольная точка',
                'verbose_name_plural': 'Контрольные точки',
            },
        ),
    ]
