# Generated by Django 3.1.2 on 2020-10-22 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_kt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='date_end',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='date_start',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
