# Generated by Django 3.1.2 on 2020-10-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20201022_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='date_end',
            field=models.CharField(max_length=100, verbose_name='мет'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='date_start',
            field=models.CharField(max_length=100, verbose_name='Прт'),
        ),
    ]
