# Generated by Django 3.1.2 on 2020-10-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20201022_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='dogovor',
            name='date_start',
            field=models.DateField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='kt',
            name='kt_end',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='kt',
            name='kt_start',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
