# Generated by Django 3.1.2 on 2020-10-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20201022_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogovor',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Пет'),
        ),
    ]
