# Generated by Django 3.1.2 on 2020-10-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_auto_20201022_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kt',
            name='docs',
        ),
        migrations.AddField(
            model_name='kt',
            name='prosrochka',
            field=models.PositiveIntegerField(default=0, verbose_name='Просрочка'),
        ),
    ]
