# Generated by Django 3.1.2 on 2020-10-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_auto_20201022_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='tip',
            field=models.CharField(default=12, max_length=100, verbose_name='Тип договора'),
            preserve_default=False,
        ),
    ]
