# Generated by Django 3.1.2 on 2020-10-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_remove_dogovor_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='type',
            field=models.CharField(default=12, max_length=100, verbose_name='Тип договора'),
            preserve_default=False,
        ),
    ]
