# Generated by Django 3.1.2 on 2020-10-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0021_dogovor_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogovor',
            name='docfile',
            field=models.FileField(default=12, upload_to='documents/', verbose_name='Доумент договора'),
            preserve_default=False,
        ),
    ]
